![](https://csie.asia.edu.tw/uploads/asset/data/6163a876063ca22598000002/logo.jpg)

# CSIE Python-100 Question Bank 資工系Python測驗題庫(2023/12/25)
* https://docs.python.org/
* https://www.w3schools.com/python/

## Data types and expressions (1-10)

1.
```
a=3;b=2
print(a**b)
```
(a) 2 (b) 3 (c) 4 (d) 9

2.
```
a=9;b=4
print(a//b)
```
(a) 1 (b) 2 (c) 3 (d) 4

3.
```
a=9;b=4
print(a%b)
```
(a) 1 (b) 2 (c) 3 (d) 4

4.
```
a=9;b=4
print(f"{a/b:.1f}")

```
(a) 2.1 (b) 2.2 (c) 2.3 (d) 2.4

5.

```
a=1.5;b=1.1
print(f"{a*b:.1f}")

```
(a) 1.5 (b) 1.6 (c) 1.7 (d) 1.8

6.

```
a=2.67;b=1.12
print(f"{a-b:.1f}")

```
(a) 1.5 (b) 1.6 (c) 1.7 (d) 1.8

7.

```
a=2.67;b=1.12
print(f"{a-b:.1f}")

```
(a) 1.5 (b) 1.6 (c) 1.7 (d) 1.8

8.
```
a=0xa;b=0x3
print(a*b)
```
(a) 10 (b) 20 (c) 30 (d) 40

9.
```
a=0xa;b=0x3
print({a*b:x})
```
(a) 10 (b) 11 (c) 1e (d) 30


10.
```
a=2
print(a<<1)
```
(a) 1 (b) 2 (c) 4 (d) 8

In [ ]:
a=3;b=2
print(a**b)

9

In [ ]:
a=9;b=4
print(a//b)

2

## String (11-20)

11.
```
a= "John"
print(len(a))
```
(a) 2 (b) 3 (c) 4 (d) 5

12.
```
a= "John"
print("n" in a)
```
(a) 3 (b) True (c) False (d) -1

13.
```
a= "John"
print(a[1:2])
```
(a) J (b) o (c) Jo (d) oh

14.
```
a= "John"
print(a[-3:-1])
```
(a) J (b) o (c) Jo (d) oh

15.
```
a= "John"
print(a.index('oh'))
```
(a) 1 (b) 2 (c) 3 (d) -1

16.
```
a, b= "John Tom".split()
print(a)
```
(a) John Tom (b) John (c) Tom (d) J

17.
```
a= "John"
print(a.find('xn'))
```
(a) 1 (b) 2 (c) 3 (d) -1

18.
```
a= "ABC"
print(a[::-1])
```
(a) A (b) C (c) ABC (d) CBA

19.
```
b = "XX YYYYY ZZZ"
print(b.count("YY"))
```
(a) -1 (b) 1 (c) 2 (d) 3


20.
```
a= "ABCDE".replace("CD","FG")
print(a[-3])
```
(a) D (b) E (c) F (d) G

## Condition and For/While Loops(21-30)

21.

```
print(10 < 9)
```
(a)1 (b) -1 (c) True (d) False

22.

```
print(10 < 9 or 8 < 9)
```
(a)1 (b) 0 (c) True (d) False

23.

```
print(10 < 9 and 8 < 9)
```
(a)1 (b) 0 (c) True (d) False

24.

```
print(10 < 9 < 8)
```
(a)1 (b) 0 (c) True (d) False

25.

```
print(10 > 9 > 8)
```
(a)1 (b) 0 (c) True (d) False

26.
```
for x in "abc":
  print(x, end='')
```
(a) a (b) b (c) abc (d) a b

27.
```
for x in range(3):
  pass
else:
  print(x)
```
(a) 0 (b) 1 (c) 2 (d) 3

28.
```
for x in "ABC":
  if x=='A':
    continue
  print(x, end='')
  break
```
(a) A (b) B (c) C (d) D

29.
```
i = 1
while i < 6:
  i += 3
print(i)
```
(a) 1 (b) 4 (c) 7 (d) 8

30.
```
i = 1
while i < 10:
  i += 3
  if i >3:
    break
print(i)
```
(a) 1 (b) 4 (c) 7 (d) 8

## Containers-list, dict, set and tuple (31-40)

31.
```
b=[1, 2, 3, 4, 5]
print(b[2])
```
(a) 1 (b) 2 (c) 3 (d) 4

32.
```
b=[1, 2, 3, 4, 5]
print(b[-4])
```
(a) 1 (b) 2 (c) 3 (d) 4

33.
```
d = [x for x in range(4)]
print(len(d))
```
(a) 1 (b) 2 (c) 3 (d) 4

34.
```
c={1, 2, 3, 3}
print(len(c))
```
(a) 1 (b) 2 (c) 3 (d) 4

35.
```
b=[1, 2]
b.append(4)
print(len(b))
```
(a) 1 (b) 2 (c) 3 (d) 4

36.
```
f={(1, 2), (3, 3)}
print(len(f))
```
(a) 1 (b) 2 (c) 3 (d) 4

37.
```
g=[1, 2] + [3, 3]
print(len(g))
```
(a) 1 (b) 2 (c) 3 (d) 4

38.
```
g=(1, 2) + (3, 4)
print(g)
```
(a) 1 (b) 2 (c) 3 (d) 4

39.
```
k={1:2, 3:4}
print(k[1])
```
(a) 1 (b) 2 (c) 3 (d) 4

40.
```
a=[1, 2, 3]
b,*c=a
print(c)
```
(a) [1, 2, 3] (b)[1, 2] (c) [2, 3] (d) [2]

## Function (41-50)



41.
```
def foo():
  return [1, 2, 3]
a=foo()
print(a[1])
```
(a) 1 (b) 2 (c) 3 (d) 4

42.
```
def foo(a, b):
  return a-b
print(foo(3,2))
```
(a) 1 (b) 2 (c) 3 (d) 4

43.
```
def foo(a, b=1):
  return a-b
print(foo(5))
```
(a) 1 (b) 2 (c) 3 (d) 4

44.
```
def foo(a=5, b=1):
  return a-b
print(foo(b=2))
```
(a) 1 (b) 2 (c) 3 (d) 4

45.
```
def factorial(x):
  if x == 1:
    return 1
  else:
    return (x * factorial(x-1))
print(factorial(2))
```
(a) 1 (b) 2 (c) 3 (d) 4

46.
```
def foo(*x):
  return max(x)*2

print(foo(0,1,2))
```
(a) 1 (b) 2 (c) 3 (d) 4

47.
```
def foo(**aa):
  return aa['x']+aa['y']
print(foo(x=1, y=2))
```
(a) 1 (b) 2 (c) 3 (d) 4

48.
```
x = lambda a : a *2
print(x(1))
```
(a) 1 (b) 2 (c) 3 (d) 4

49.
```
def foo(n):
  return lambda a : a * n
doubler = foo(2)
print(doubler(3))
```
(a) 3 (b) 6 (c) 9 (d) 12

50.
```
a=[lambda x: x*x, lambda x: x*3]
print(a[1](2))
```
(a) 3 (b) 6 (c) 9 (d) 12

## Built-in Functions (51-70)

### enumerate(), zip(), sorted(), min() and max()


51.
```
seasons = ['Spring', 'Summer', 'Fall', 'Winter']
a=list(enumerate(seasons))
print(a[1])
```
(a) 'Spring' (b) 'Summer' (c) (0, 'Spring') (d) (1, 'Summer')

52.
```
seasons = ['Spring', 'Summer', 'Fall', 'Winter']
a=list(enumerate(seasons,start=1))
print(a[0])
```
(a) 'Spring' (b) 'Summer' (c) (1, 'Spring') (d) (2, 'Summer')

53.
```
seasons = ['Spring', 'Summer', 'Fall', 'Winter']
for i, x in enumerate(seasons):
  print(x)
  break
```
(a) 'Spring' (b) 'Summer' (c) (0, 'Spring') (d) (1, 'Summer')

54.
```
a = [1, 2, 3]
b = ['x', 'y', 'z']
c = list(zip(a,b))
print(c[1])
```
(a) x (b) '2y' (c) (2, 'y') (d) y

55.
```
a = [1, 2, 3]
b = ['x', 'y', 'z']
c = dict(zip(a,b))
print(c[1])
```
(a) x (b) '2y' (c) (2, 'y') (d) y

56.
```
a = [1, 2, 3]
b = ['x', 'y', 'z']
c, d = zip(*zip(a,b))  
print(d[1])
```
(a) x (b) '2y' (c) (2, 'y') (d) y

57.

```
a = [1, 3, 2, 5]
b = sorted(a)
print(b[2])
```
(a) 1 (b) 3 (c) 2 (d) 5

58.

```
a = [1, 3, 2, 5]
b = sorted(a, reverse=True)
print(b[2])
```
(a) 1 (b) 3 (c) 2 (d) 5

59.

```
a = [1, 3, 2, 5]
print(max(a))
```
(a) 1 (b) 3 (c) 2 (d) 5

60.

```
a = [1, 3, 2, 5]
print(min(a))
```
(a) 1 (b) 3 (c) 2 (d) 5

### range(), map(), eval() and filter()



61.
```
a=range(3)
print(list(a))
```
(a) [3] (b) 1 2 3 (c) 0, 1, 2 (d) [0, 1, 2]

62.
```
a=range(1,3)
print(list(a))
```
(a) [1, 2] (b) 1 2 (c) 0, 1 (d) [0, 1, 2]

63.
```
a=range(1, 5, 2)
print(list(a))
```
(a) [1, 3] (b) 1 3 (c) 0, 2 (d) [1, 2, 3]

64.
```
a=range(1, 5, 2)
print(list(a))
```
(a) [1, 3] (b) 1 3 (c) 0, 2 (d) [1, 2, 3]

65.
```
a=range(1, -5, -2)
print(list(a))
```
(a) [1, -3] (b) [-1, -2, -3] (c) [1, -1, -3, -5] (d) [1, -1, -3]

66.
```
a=list(map(int, "1 2 3".split()))
print(a[0])
```
(a) 1 (b) 2 (c) 3 (d) 4

67.
```
a=list(map(float, [1, 2, 3])
print(a[2])
```
(a) 1.0 (b) 2.0 (c) 3.0 (d) 4.0

68.
```
a=list(map(lambda x: x*2, [1, 2, 3]))
print(a[0])
```
(a) 1 (b) 2 (c) 3 (d) 4


69.
```
x = 2
print(eval( '2*x' ))
```
(a) 1 (b) 2 (c) 3 (d) 4

70.
```
a=list(filter(lambda x: x % 3 == 2, range(10)))
print(a[0])
```
(a) 1 (b) 2 (c) 3 (d) 4

## Class and object (71-80)

71.
```
# Create Object
class MyClass:
  x = 3
p1 = MyClass()
print(p1.x)
```
(a) 1 (b) 2 (c) 3 (d) 4

72.
```
# Create Object
class Employee:
  def __init__(self, name, age,salary):
    self.name = name
    self.age = age
    self.salary = 20000
E1 = Employee("Alex", 23, 20000)

print(E1.name)
```
(a) "Alex" (b) Alex (c) 23 (d) "23"

73.
```
# Create Object
class Employee:
  def __init__(self, name, age,salary):
    self.name = name
    self.age = age
    self.salary = 20000
  def __str__(self):
    return self.name
E1 = Employee("Alex", 23, 20000)

print(E1)
```
(a) "Alex" (b) Alex (c) 23 (d) "23"

74.
```
class Person:
  def __init__(self, name, id):
    self.name = name
    self.id = id
  def printname(self):
    print(self.name)
x = Person("John", '133456')
x.printname()
```
(a) "John" (b) John (c) 133456 (d) "133456"

75.
```
# Inheritance
class Person:
  def __init__(self, name, id):
    self.name = name
    self.id = id
  def printname(self):
    print(self.name)
class Student(Person):
  def __init__(self, name, id):
    self.name = name.upper()
    self.id = id
x = Student("John", '133456')
x.printname()
```
(a) "John" (b) John (c) JOHN (d) "JOHN"

76.
```
# Inheritance
class Person:
  def __init__(self, name, id):
    self.name = name
    self.id = id
  def printname(self):
    print(self.name)
class Student(Person):
  def __init__(self, name, id):
    super().__init__(name, id)
x = Student("John", '133456')
x.printname()
```
(a) "John" (b) John (c) JOHN (d) "JOHN"

77.
```
class Person:
  def __init__(self, name, id):
    self.name = name
    self.id = id
x = Person("John", '133456')
y = Person("John", '133456')
print(x==y)
```
(a) Yes (b) No (c) True (d) False

78.
```
# Inheritance
class Person:
  def __init__(self, name, id):
    self.name = name
    self.id = id
  def printname(self):
    print(self.name)
class Student(Person):
  def __init__(self, name, id):
    super().__init__(name, id)
x = Student("John", '133456')
y = x
print(x==y)
```
(a) Yes (b) No (c) True (d) False

79.
```
def my_decorator(func):
    print('A->', end="")
    return func

@my_decorator
def my_func():
    print('B->', end="")

my_func()
```
(a) A-> (b) B-> (C) A->B-> (D)B->A->

80.
```
import copy
class Person:
  def __init__(self, name, id):
    self.name = name
    self.id = id
  def printname(self):
    print(self.name)
class Student(Person):
  def __init__(self, name, id):
    super().__init__(name, id)
x = Student("John", '133456')
y = copy.deepcopy(x)
print(x==y)
```
(a) Yes (b) No (c) True (d) False

## The Python Standard Library(81-100) Optional

### RegEx
81.
```
import re
pattern = '^s\w+x$'
test_string = 'school'
result = re.match(pattern, test_string)
print(type(result))
```
(a) <class 're.Match'> (b) <class 're.Search'> (c) <class 'NoneType'> (d) None

82.
```
import re
pattern = '^s\w+l$'
test_string = 'school'
result = re.match(pattern, test_string)
print(type(result))
```
(a) <class 're.Match'> (b) <class 're.Search'> (c) <class 'NoneType'> (d) None

83.
```
import re
pattern = '^s\w+l$'
test_string = 'school'
result = re.match(pattern, test_string)
print(type(result))
```
(a) <class 're.Match'> (b) <class 're.Search'> (c) <class 'NoneType'> (d) None

84.
```
import re
pattern = '^s\w+o'
test_string = 'school'
result = re.match(pattern, test_string)
print(result.group())
```
(a) scho (b) schoo (c) school (d) None

85.
```
import re
print(re.search('my', 'myPython').span())
```
(a) (0) (b) (2) (c) (0, 2) (d) None

### JSON
86.
```
import json
y = json.loads('{ "name":"John", "age":30, "id":"012345"}')
print(y["name"])

```
(a) John (b) 30 (c) id (d) 012345

87.
```
import json
j = {'id': "012345"}
print(json.dumps(j))

```
(a) id (b) ["id"] (c) {"id": "012345"} (d) 012345

88.
```
import json
a = "[[0], [1]]"
b = json.loads(a)
print(type(b))

```
(a) <class 'list'> (b) <class 'dict'> (c) <class 'NoneType'> (d) None

89.
```
import json
a = '{"1":"John", "2":"Mary"}'
b = json.loads(a)
print(type(b))

```
(a) <class 'list'> (b) <class 'dict'> (c) <class 'NoneType'> (d) None

### Datetime

90.
```
import datetime
x = datetime.datetime(2020, 5, 17)
print(x.strftime("%d"))
```
(a) 2020 (b) 5 (c) 17 (d) Sunday

91.
```
import datetime
x = datetime.datetime(2020, 5, 17)
print(x.strftime("%Y"))
```
(a) 2020 (b) 5 (c) 17 (d) Sunday

92.
```
import datetime
x = datetime.datetime(2020, 5, 17)
y = x+ datetime.timedelta(days=365)
print(y.strftime("%d"))
```
(a) 2020 (b) 5 (c) 17 (d) Sunday

93.
```
import calendar
print(calendar.isleap(2020))
```
(a) Yes (b) No (c) True (d) False

94.
```
import calendar
print(calendar.month_name[1])
```
(a) January (b) February (c) March (d) April

95.
```
import calendar
print(calendar.day_name[0])
```
(a) Sunday (b) Monday (c) Tuesday (d) Friday

### random
96.
```
import random
x=random.uniform(2,3)
print(x)
```
以下何者可能是 x的值:

(a) 1.33 (b) 2.5 (c) 3.3 (d) -3.6


97.
```
import random
a=random.randint(1,10)
print(a)
```
以下何者可能是 a的值:

(a) 1.33 (b) 5 (c) 100 (d) -3

98.
```
import random
b=random.random()
print(b)
```
以下何者可能是 b的值:

(a) 1.33 (b) 2.5 (c) 0.65 (d) -1.2

99.
```
import random
c=random.choice('xyz%^&')
print(c)
```
以下何者可能是 c的值:

(a) x (b) ! (c) 1 (d) -3

100.
```
import random
d=[1,2,3]
random.shuffle(d)
print(d)
```
以下何者可能是 d的值:

(a) [1,-2,3] (b) [2,1,3] (c) [4,5,6] (d) [6,4,5]